### ISSUE TITLE
Deadlock when create_partitioner fails (assertion fails) in debug mode

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3460]
## Expected Behavior

No deadlock. Exception should be thrown normally.

## Actual Behavior

Deadlock. No output.

## Steps to Reproduce the Problem

Run an HPX executable in debug mode with `HPX_MAX_CPU_COUNT` lower than the real number of PUs on the machine, but anything that throws/asserts inside the partitioner constructor would lead to the same problem. Stack trace below (important frames are 5 and 18):

```
#0  0x00002aaaae069a7c in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00002aaaae06c3e0 in __lll_lock_elision () from /lib64/libpthread.so.0
#2  0x00002aaaab3b85e9 in __gthread_mutex_lock (__mutex=0x2aaaace09f00 <hpx::resource::detail::partitioner_mtx()::mtx>) at /opt/gcc/7.3.0/snos/include/g++/x86_64-suse-linux/bits/gthr-default.h:748
#3  0x00002aaaab3bf810 in std::mutex::lock (this=0x2aaaace09f00 <hpx::resource::detail::partitioner_mtx()::mtx>) at /opt/gcc/7.3.0/snos/include/g++/bits/std_mutex.h:103
#4  0x00002aaaab3c1110 in std::lock_guard<std::mutex>::lock_guard (this=0x7fffffff4920, __m=...) at /opt/gcc/7.3.0/snos/include/g++/bits/std_mutex.h:162
#5  0x00002aaaabb6c430 in hpx::resource::detail::get_partitioner () at /apps/daint/UES/simbergm/src/hpx/src/runtime/resource/partitioner.cpp:134
#6  0x00002aaaabb6c706 in hpx::resource::is_partitioner_valid () at /apps/daint/UES/simbergm/src/hpx/src/runtime/resource/partitioner.cpp:193
#7  0x00002aaaab3bc351 in hpx::get_config_entry (key=..., dflt=...) at /apps/daint/UES/simbergm/src/hpx/src/runtime.cpp:941
#8  0x00002aaaab3431da in hpx::detail::assertion_failed_msg (msg=0x2aaaac158968 "s <= CHAR_BIT * sizeof(mask_type)", expr=0x2aaaac158968 "s <= CHAR_BIT * sizeof(mask_type)", function=0x2aaaac161740 <hpx::threads::resize(unsigned long&, unsigned long)::__PRETTY_FUNCTION__> "void hpx::threads::resize(hpx::threads::mask_type&, std::size_t)", file=0x2aaaac158920 "/apps/daint/UES/simbergm/src/hpx/hpx/runtime/threads/cpu_mask.hpp", line=79) at /apps/daint/UES/simbergm/src/hpx/src/exception.cpp:458
#9  0x00002aaaab3430db in hpx::detail::assertion_failed (expr=0x2aaaac158968 "s <= CHAR_BIT * sizeof(mask_type)", function=0x2aaaac161740 <hpx::threads::resize(unsigned long&, unsigned long)::__PRETTY_FUNCTION__> "void hpx::threads::resize(hpx::threads::mask_type&, std::size_t)", file=0x2aaaac158920 "/apps/daint/UES/simbergm/src/hpx/hpx/runtime/threads/cpu_mask.hpp", line=79) at /apps/daint/UES/simbergm/src/hpx/src/exception.cpp:451
#10 0x00002aaaab344b9d in hpx::assertion_failed (expr=0x2aaaac158968 "s <= CHAR_BIT * sizeof(mask_type)", function=0x2aaaac161740 <hpx::threads::resize(unsigned long&, unsigned long)::__PRETTY_FUNCTION__> "void hpx::threads::resize(hpx::threads::mask_type&, std::size_t)", file=0x2aaaac158920 "/apps/daint/UES/simbergm/src/hpx/hpx/runtime/threads/cpu_mask.hpp", line=79) at /apps/daint/UES/simbergm/src/hpx/src/exception.cpp:838
#11 0x00002aaaab3d2557 in hpx::threads::resize (s=72) at /apps/daint/UES/simbergm/src/hpx/hpx/runtime/threads/cpu_mask.hpp:79
#12 0x00002aaaabcdb3b6 in hpx::threads::topology::init_machine_affinity_mask (this=0x2aaaace047c0 <hpx::util::static_<hpx::threads::topology, hpx::threads::topology_tag>::get_reference()::t>) at /apps/daint/UES/simbergm/src/hpx/src/runtime/threads/topology.cpp:931
#13 0x00002aaaabcd879b in hpx::threads::topology::topology (this=0x2aaaace047c0 <hpx::util::static_<hpx::threads::topology, hpx::threads::topology_tag>::get_reference()::t>) at /apps/daint/UES/simbergm/src/hpx/src/runtime/threads/topology.cpp:249
#14 0x00002aaaab4bf80e in hpx::util::static_<hpx::threads::topology, hpx::threads::topology_tag>::get_reference () at /apps/daint/UES/simbergm/src/hpx/hpx/util/static.hpp:76
#15 0x00002aaaab4be0f1 in hpx::util::static_<hpx::threads::topology, hpx::threads::topology_tag>::static_ (this=0x7fffffff4fff) at /apps/daint/UES/simbergm/src/hpx/hpx/util/static.hpp:50
#16 0x00002aaaab4bc868 in hpx::threads::create_topology () at /apps/daint/UES/simbergm/src/hpx/hpx/runtime/threads/topology.hpp:407
#17 0x00002aaaabb5f66d in hpx::resource::detail::partitioner::partitioner (this=0xf3c400) at /apps/daint/UES/simbergm/src/hpx/src/runtime/resource/detail/detail_partitioner.cpp:220
#18 0x00002aaaabb6c461 in hpx::resource::detail::get_partitioner () at /apps/daint/UES/simbergm/src/hpx/src/runtime/resource/partitioner.cpp:137
#19 0x00002aaaabb6c755 in hpx::resource::detail::create_partitioner(hpx::util::function<int (boost::program_options::variables_map&), false> const&, boost::program_options::options_description const&, int, char**, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, hpx::resource::partitioner_mode, hpx::runtime_mode, bool) (f=..., desc_cmdline=..., argc=2, argv=0x7fffffff57e8, ini_config=..., rpmode=hpx::resource::mode_default, mode=hpx::runtime_mode_default, check=true) at /apps/daint/UES/simbergm/src/hpx/src/runtime/resource/partitioner.cpp:207
#20 0x00000000004353ef in hpx::resource::detail::create_partitioner (argc=2, argv=0x7fffffff57e8, ini_config=..., rpmode=hpx::resource::mode_default, mode=hpx::runtime_mode_default, check=true) at /apps/daint/UES/simbergm/src/hpx/hpx/runtime/resource/detail/create_partitioner.hpp:110
#21 0x0000000000435523 in hpx::resource::partitioner::partitioner (this=0x7fffffff5538, argc=2, argv=0x7fffffff57e8, ini_config=..., rpmode=hpx::resource::mode_default, mode=hpx::runtime_mode_default) at /apps/daint/UES/simbergm/src/hpx/hpx/runtime/resource/partitioner.hpp:173
#22 0x000000000042b2fe in test_scheduler (argc=2, argv=0x7fffffff57e8, scheduler=hpx::resource::local) at /apps/daint/UES/simbergm/src/hpx/tests/unit/resource/suspend_thread_timed.cpp:107
#23 0x000000000042b592 in main (argc=2, argv=0x7fffffff57e8) at /apps/daint/UES/simbergm/src/hpx/tests/unit/resource/suspend_thread_timed.cpp:145
```

I do have a memory of this working correctly before, so I'm wondering if anyone knows what changed? A recursive mutex alone would not be alone since that just leads to HPX trying to create the partitioner twice. @hkaiser any ideas?

**Comment by hkaiser** [comment]
@msimberg I'll try to have a look.

**Comment by hkaiser** [comment]
@msimberg this should have been fixed by merging #3468. Could you recheck, please?
