### ISSUE TITLE
hpx segfault after dca finish runs 

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/hpx#4879]
## Expected Behavior

... Please describe the behavior you would have expected.

## Actual Behavior

I run dca with hpx threading support on Cori GPU node, and found that after dca has successfully prints the finish, hpx gives segfault. Here is the backtrace:

```
.... dca run until the end....
Finish time: 31-07-2020 11:50:06

[Thread 0x2aaacfcc4700 (LWP 12719) exited]
[Thread 0x2aaacc40c700 (LWP 12718) exited]
[Thread 0x2aaacc007700 (LWP 12717) exited]
[Thread 0x2aaacb401700 (LWP 12713) exited]
[Thread 0x2aaacb602700 (LWP 12714) exited]
[Thread 0x2aaacb200700 (LWP 12712) exited]
[Thread 0x2aaaca401700 (LWP 12711) exited]
[Thread 0x2aaac9e00700 (LWP 12710) exited]
[Thread 0x2aaac8c02700 (LWP 12708) exited]

Thread 16 "main_dca" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x2aaacba04700 (LWP 12716)]
0x00002aaad172b740 in ?? ()
Missing separate debuginfos, use: zypper install libblas3-debuginfo-3.5.0-lp150.3.3.1.x86_64 libfftw3-3-debuginfo-3.3.6-lp150.3.3.x86_64 libgfortran4-debuginfo-7.4.1+r275405-lp150.12.1.x86_64 liblapack3-debuginfo-3.5.0-lp150.3.3.1.x86_64 libnl3-200-debuginfo-3.3.0-lp150.1.14.x86_64 libnuma1-debuginfo-2.0.11-lp150.2.4.x86_64 libopenblas_pthreads0-debuginfo-0.2.20-lp150.5.14.x86_64 libz1-debuginfo-1.2.11-lp150.11.1.x86_64 nvidia-computeG04-debuginfo-440.95.01-0.x86_64
(gdb) bt
#0  0x00002aaad172b740 in ?? ()
#1  0x00002aaac0e75698 in __nptl_deallocate_tsd.part.5 ()
   from /lib64/libpthread.so.0
#2  0x00002aaac0e766bc in start_thread () from /lib64/libpthread.so.0
#3  0x00002aaac1185a2f in clone () from /lib64/libc.so.6

```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

## Specifications

... Please describe your environment

  - HPX Version:086c72e2fc928df8340290e88d6c6f8e17c5aa10
  - Platform (compiler, OS): gcc/8.2.0, Intel Xeon Gold 6148 ('Skylake') @ 2.40 GHz

```
    /global/homes/w/weile/dev/src/spack/opt/spack/cray-cnl7-haswell/gcc-8.2.0/cmake-3.17.3-ukmglmvwjw32w3swl42d22lxuflgreye/bin/cmake -G "Ninja" \
            -DCMAKE_MAKE_PROGRAM=/global/homes/w/weile/dev/src/ninja/build-cmake/ninja \
            -DCMAKE_BUILD_TYPE=RelWithDelInfo                                   \
            -DBOOST_ROOT=$BOOST_PATH                                            \
            -DHPX_WITH_CXX17=ON                                                 \
            -DCMAKE_CXX_FLAGS=$CXXFLAGS                                         \
            -DHWLOC_ROOT=$HWLOC_PATH                                            \
            -DJEMALLOC_ROOT=$JEMALLOC_PATH                                      \
            -DHPX_WITH_MALLOC=JEMALLOC                                          \
            -DHPX_WITH_HWLOC=ON                                                 \
            -DHPX_WITH_THREAD_IDLE_RATES=ON                                     \
            -DHPX_WITH_NETWORKING=OFF                                           \
            -DHPX_WITH_PARCELPORT_MPI=OFF                                       \
            -DHPX_WITH_PARCELPORT_TCP=OFF                                       \
            -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH                                \
            -DHPX_WITH_EXAMPLES=ON                                              \
            -DHPX_WITH_TOOLS=OFF                                                        \
            -DHPX_WITH_TESTS=OFF                                                \
            -DHPX_WITH_EXAMPLES=OFF                                             \
            -DHPX_WITH_TESTS_BENCHMARKS=OFF                                     \
            -DHPX_WITH_TESTS_REGRESSIONS=OFF                                    \
            -DHPX_WITH_TESTS_UNIT=OFF                                           \
            -DHPX_WITH_CUDA=OFF                                                 \
            -Wdev                                                               \
            $HPX_PATH

```

**Comment by weilewei** [comment]
@hkaiser do you have any other suggestions? I could not move forward with DCA + HPX on Cori due to this bug

**Comment by weilewei** [comment]
On CoriGPU, there are two hpx tests failed, does this failures relate to the segfault in this ticket?

```
50: Test command: /usr/bin/python "/global/homes/w/weile/dev/src/hpx_apex/hpx/build_hpx_apex_RelWithDebInfo/bin/hpxrun.py" "/global/homes/w/weile/dev/src/hpx_apex/hpx/build_hpx_apex_RelWithDebInfo/bin/use_all_cores_2262_test" "-e" "0" "-t" "1" "-v" "--"
50: Test timeout computed to be: 120
50: Delta computed to be: -10095
50: ../tests/regressions/util/use_all_cores_2262.cpp(21): test 'hpx::threads::hardware_concurrency() == hpx::get_os_thread_count()' failed in function 'int hpx_main(int, char**)': '20' != '10'
50: 0 sanity checks and 1 test failed.
50: Base command is "/global/homes/w/weile/dev/src/hpx_apex/hpx/build_hpx_apex_RelWithDebInfo/bin/use_all_cores_2262_test --hpx:threads=1"
50: Executing command: /global/homes/w/weile/dev/src/hpx_apex/hpx/build_hpx_apex_RelWithDebInfo/bin/use_all_cores_2262_test --hpx:threads=1
 50/146 Test  #50: tests.regressions.util.use_all_cores_2262 ...................................***Failed    0.18 sec
```

```
42: Test command: /usr/bin/python "/global/homes/w/weile/dev/src/hpx_apex/hpx/build_hpx_apex_RelWithDebInfo/bin/hpxrun.py" "/global/homes/w/weile/dev/src/hpx_apex/hpx/build_hpx_apex_RelWithDebInfo/bin/thread_suspend_duration_test" "-e" "0" "-t" "1" "-v" "--"
42: Test timeout computed to be: 120
42: Delta computed to be: -9494
42: Base command is "/global/homes/w/weile/dev/src/hpx_apex/hpx/build_hpx_apex_RelWithDebInfo/bin/thread_suspend_duration_test --hpx:threads=1"
42: Executing command: /global/homes/w/weile/dev/src/hpx_apex/hpx/build_hpx_apex_RelWithDebInfo/bin/thread_suspend_duration_test --hpx:threads=1
 42/146 Test  #42: tests.regressions.threads.thread_suspend_duration ...........................   Passed    0.61 sec
test 43
        Start  43: tests.regressions.threads.threads_all_1422

```

**Comment by msimberg** [comment]
@weilewei please try to find out what is starting a thread at the end of the execution. Does this happen also without HPX threading in DCA? It's possible, but unlikely that this is caused by HPX. We do not start any threads after the runtime is started in HPX. This is happening either during HPX shutdown or after HPX has already been shut down.

**Comment by weilewei** [comment]
@msimberg This situation does not happen when DCA (+MPI support [default]) builds without HPX support, also does not happen when DCA (disable MPI support) builds with HPX support. Only happens when DCA w/ MPI support + HPX threading. Is there anyway to know what starts a thread at the end of execution? Backtrace gives no useful information.

**Comment by hkaiser** [comment]
@weilewei has this been resolved?

**Comment by weilewei** [comment]
Cori is completely down these weeks, I will check it later and let you
know.
