### ISSUE TITLE
hpx::distributed:barrier errors

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#5828]
running test_barrier many times reveals problems such as this one. The segfaults/assertion failures happen in different places - indicating some kind of race.
```
mpiexec -n 2  /home/biddisco/build/hpx-rma/bin/barrier_test --pxthreads=8  --iterations=1000
```

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737124470784) at pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737124470784) at pthread_kill.c:80
#2  __GI___pthread_kill (threadid=140737124470784, signo=signo@entry=6) at pthread_kill.c:91
#3  0x00007ffff6072476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff60587b7 in __GI_abort () at abort.c:79
#5  0x00007ffff6b882d4 in hpx::detail::assertion_handler (loc=..., expr=0x7ffff7b106d1 "phase_ != old_phase", msg="") at /home/biddisco/src/hpx-rma/libs/core/runtime_local/src/runtime_handlers.cpp:75
#6  0x00007ffff7a54a6f in hpx::assertion::detail::handle_assert (loc=..., expr=0x7ffff7b106d1 "phase_ != old_phase", msg="") at /home/biddisco/src/hpx-rma/libs/core/assertion/src/assertion.cpp:47
#7  0x00007ffff76a2513 in hpx::barrier<hpx::detail::empty_oncompletion>::wait (this=0x7ffff23a6688, old_phase=@0x7fffe45c15c7: true) at /home/biddisco/src/hpx-rma/libs/core/synchronization/include/hpx/synchronization/barrier.hpp:211
#8  0x00007ffff76a0f1a in hpx::barrier<hpx::detail::empty_oncompletion>::arrive_and_wait (this=0x7ffff23a6688) at /home/biddisco/src/hpx-rma/libs/core/synchronization/include/hpx/synchronization/barrier.hpp:218
#9  0x00007ffff768ff02 in hpx::distributed::detail::barrier_node::set_event (this=0x7ffff23a6600) at /home/biddisco/src/hpx-rma/libs/full/collectives/src/detail/barrier_node.cpp:308
#10 0x00007ffff757db2b in hpx::lcos::base_lco::set_event_nonvirt (this=0x7ffff23a6600) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/src/base_lco.cpp:46
#11 0x00007ffff75873b6 in hpx::actions::detail::component_invoke<hpx::lcos::base_lco, void, void ()>(void*, int, void (hpx::lcos::base_lco::*)()) (lva=0x7fffebda5cc8, f=(void (hpx::lcos::base_lco::*)(hpx::lcos::base_lco * const)) 0x7ffff757db08 <hpx::lcos::base_lco::set_event_nonvirt()>) at /home/biddisco/src/hpx-rma/libs/full/actions_base/include/hpx/actions_base/component_action.hpp:70
#12 0x00007ffff7586e80 in hpx::actions::action<void (hpx::lcos::base_lco::*)(), &hpx::lcos::base_lco::set_event_nonvirt, hpx::lcos::base_lco::set_event_action>::invoke<>(void*, int) (lva=0x7fffebda5cc8, comptype=6146) at /home/biddisco/src/hpx-rma/libs/full/actions_base/include/hpx/actions_base/component_action.hpp:103
#13 0x00007ffff7585bb1 in hpx::actions::basic_action<hpx::lcos::base_lco, void (), hpx::lcos::base_lco::set_event_action>::invoker<>(void*, int) (lva=0x7fffebda5cc8, comptype=6146) at /home/biddisco/src/hpx-rma/libs/full/actions_base/include/hpx/actions_base/basic_action.hpp:277
#14 0x00007ffff767466a in hpx::actions::basic_action<hpx::lcos::base_lco, void (), hpx::lcos::base_lco::set_event_action>::execute_function<>(void*, int) (comptype=6146, lva=0x7fffebda5cc8) at /home/biddisco/src/hpx-rma/libs/full/actions_base/include/hpx/actions_base/basic_action.hpp:340
#15 hpx::lcos::packaged_action<hpx::lcos::base_lco::set_event_action, void, true>::apply<>(hpx::naming::address&&, hpx::naming::id_type const&) (this=0x7fffe45c18c0, addr=..., id=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/packaged_action.hpp:513
#16 0x00007ffff76727f0 in hpx::detail::async_remote_impl<hpx::lcos::base_lco::set_event_action> (id=..., addr=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/detail/async_implementations.hpp:254
#17 0x00007ffff7670505 in hpx::detail::async_impl<hpx::lcos::base_lco::set_event_action, hpx::detail::async_policy const&> (policy=..., id=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/detail/async_implementations.hpp:459
#18 0x00007ffff768e6aa in hpx::detail::async_action_dispatch<hpx::lcos::base_lco::set_event_action, hpx::detail::async_policy, void>::call<hpx::detail::async_policy const&> (id=..., launch_policy=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/async.hpp:73
#19 hpx::async<hpx::lcos::base_lco::set_event_action, hpx::detail::async_policy const&, hpx::naming::id_type const&> (f=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/async.hpp:200
#20 hpx::detail::async_dispatch<hpx::lcos::base_lco::set_event_action, void>::call<hpx::lcos::base_lco, void (), hpx::lcos::base_lco::set_event_action>(hpx::actions::basic_action<hpx::lcos::base_lco, void (), hpx::lcos::base_lco::set_event_action> const&, hpx::naming::id_type const&) (id=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/async.hpp:220
#21 hpx::async<hpx::lcos::base_lco::set_event_action&, hpx::naming::id_type&> (f=...) at /home/biddisco/src/hpx-rma/libs/core/async_base/include/hpx/async_base/async.hpp:25
#22 hpx::distributed::detail::barrier_node::wait (this=0x7fffee63dc00, async=true) at /home/biddisco/src/hpx-rma/libs/full/collectives/src/detail/barrier_node.cpp:109
#23 0x00007ffff764035a in hpx::distributed::barrier::wait (this=0x7fffe45c1cd8) at /home/biddisco/src/hpx-rma/libs/full/collectives/src/barrier.cpp:119
#24 0x00007ffff7640680 in hpx::distributed::barrier::release (this=0x7fffe45c1cd8) at /home/biddisco/src/hpx-rma/libs/full/collectives/src/barrier.cpp:147
#25 0x00007ffff764025a in hpx::distributed::barrier::~barrier (this=0x7fffe45c1cd8, __in_chrg=<optimized out>) at /home/biddisco/src/hpx-rma/libs/full/collectives/src/barrier.cpp:109
#26 0x00005555555712da in barrier_test (num=65, rank=51, c=...) at /home/biddisco/src/hpx-rma/libs/full/collectives/tests/unit/barrier.cpp:33
#27 0x0000555555582ae3 in hpx::util::detail::deferred<void (*)(unsigned long, unsigned long, std::atomic<unsigned long>&), hpx::util::pack_c<unsigned long, 0ul, 1ul, 2ul>, unsigned long, unsigned long, std::atomic<unsigned long>&>::operator() (this=0x7fffed056fa0) at /home/biddisco/src/hpx-rma/libs/core/functional/include/hpx/functional/deferred_call.hpp:87
#28 hpx::lcos::local::detail::task_object<void, hpx::util::detail::deferred<void (*)(unsigned long, unsigned long, std::atomic<unsigned long>&), hpx::util::pack_c<unsigned long, 0ul, 1ul, 2ul>, unsigned long, unsigned long, std::atomic<unsigned long>&>, void, hpx::lcos::detail::task_base<void> >::do_run()::{lambda()#1}::operator()() const (__closure=0x7fffe45c1db8) at /home/biddisco/src/hpx-rma/libs/core/futures/include/hpx/futures/futures_factory.hpp:80
#29 0x0000555555582c27 in hpx::detail::try_catch_exception_ptr<hpx::lcos::local::detail::task_object<void, hpx::util::detail::deferred<void (*)(unsigned long, unsigned long, std::atomic<unsigned long>&), hpx::util::pack_c<unsigned long, 0ul, 1ul, 2ul>, unsigned long, unsigned long, std::atomic<unsigned long>&>, void, hpx::lcos::detail::task_base<void> >::do_run()::{lambda()#1}, hpx::lcos::local::detail::task_object<void, hpx::util::detail::deferred<void (*)(unsigned long, unsigned long, std::atomic<unsigned long>&), hpx::util::pack_c<unsigned long, 0ul, 1ul, 2ul>, unsigned long, unsigned long, std::atomic<unsigned long>&>, void, hpx::lcos::detail::task_base<void> >::do_run()::{lambda(std::__exception_ptr::exception_ptr)#2}>(hpx::lcos::local::detail::task_object<void, hpx::util::detail::deferred<void (*)(unsigned long, unsigned long, std::atomic<unsigned long>&), hpx::util::pack_c<unsigned long, 0ul, 1ul, 2ul>, unsigned long, unsigned long, std::atomic<unsigned long>&>, void, hpx::lcos::detail::task_base<void> >::do_run()::{lambda()#1}&&, hpx::lcos::local::detail::task_object<void, hpx::util::detail::deferred<void (*)(unsigned long, unsigned long, std::atomic<unsigned long>&), hpx::util::pack_c<unsigned long, 0ul, 1ul, 2ul>, unsigned long, unsigned long, std::atomic<unsigned long>&>, void, hpx::lcos::detail::task_base<void> >::do_run()::{lambda(std::__exception_ptr::exception_ptr)#2}&&) (c=..., t=...) at /home/biddisco/src/hpx-rma/libs/core/errors/include/hpx/errors/try_catch_exception_ptr.hpp:36
#30 hpx::lcos::local::detail::task_object<void, hpx::util::detail::deferred<void (*)(unsigned long, unsigned long, std::atomic<unsigned long>&), hpx::util::pack_c<unsigned long, 0ul, 1ul, 2ul>, unsigned long, unsigned long, std::atomic<unsigned long>&>, void, hpx::lcos::detail::task_base<void> >::do_run (this=0x7fffed056ec0) at /home/biddisco/src/hpx-rma/libs/core/futures/include/hpx/futures/futures_factory.hpp:76
#31 0x0000555555583786 in hpx::lcos::detail::task_base<void>::run_impl (this_=...) at /home/biddisco/src/hpx-rma/libs/core/futures/include/hpx/futures/detail/future_data.hpp:916
#32 0x0000555555584e65 in hpx::util::detail::deferred<void (*)(hpx::memory::intrusive_ptr<hpx::lcos::detail::task_base<void> >), hpx::util::pack_c<unsigned long, 0ul>, hpx::memory::intrusive_ptr<hpx::lcos::detail::task_base<void> > >::operator() (this=0x7fffebd4a148) at /home/biddisco/src/hpx-rma/libs/core/functional/include/hpx/functional/deferred_call.hpp:87
#33 hpx::threads::detail::thread_function_nullary<hpx::util::detail::deferred<void (*)(hpx::memory::intrusive_ptr<hpx::lcos::detail::task_base<void> >), hpx::util::pack_c<unsigned long, 0ul>, hpx::memory::intrusive_ptr<hpx::lcos::detail::task_base<void> > > >::operator() (this=0x7fffebd4a148) at /home/biddisco/src/hpx-rma/libs/core/threading_base/include/hpx/threading_base/register_thread.hpp:78
#34 0x0000555555584d2a in hpx::util::detail::callable_vtable<std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> (hpx::threads::thread_restart_state)>::_invoke<hpx::threads::detail::thread_function_nullary<hpx::util::detail::deferred<void (*)(hpx::memory::intrusive_ptr<hpx::lcos::detail::task_base<void> >), hpx::util::pack_c<unsigned long, 0ul>, hpx::memory::intrusive_ptr<hpx::lcos::detail::task_base<void> > > > >(void*, hpx::threads::thread_restart_state&&) (f=0x7fffebd4a148, vs#0=@0x7fffe45c1ec3: hpx::threads::thread_restart_state::signaled) at /home/biddisco/src/hpx-rma/libs/core/functional/include/hpx/functional/detail/vtable/callable_vtable.hpp:93
#35 0x00007ffff6a9ee31 in hpx::util::detail::basic_function<std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> (hpx::threads::thread_restart_state), false, false>::operator()(hpx::threads::thread_restart_state) const (vs#0=hpx::threads::thread_restart_state::signaled, this=0x7fffebd4a138) at /home/biddisco/src/hpx-rma/libs/core/functional/include/hpx/functional/detail/basic_function.hpp:228
#36 hpx::threads::coroutines::detail::coroutine_impl::operator() (this=0x7fffebd4a0d0) at /home/biddisco/src/hpx-rma/libs/core/coroutines/src/detail/coroutine_impl.cpp:74
#37 0x00007ffff6a9e84d in hpx::threads::coroutines::detail::lx::trampoline<hpx::threads::coroutines::detail::coroutine_impl> (fun=0x7fffebd4a0d0) at /home/biddisco/src/hpx-rma/libs/core/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp:179
#38 0x0000000000000000 in ?? ()
```

**Comment by hkaiser** [comment]
@biddisco thanks for this report. I have not seen this problem before - will investigate.

**Comment by gonidelis** [comment]
@hkaiser  Shouldn't we put this in the 1.8 milestone?
