### ISSUE TITLE
Distributed execution crash

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#5832]
Here is a stacktrace of an example of a segfault when running using the mpi parcelport on 4 nodes .... 
```
#0  0x000055555ede6600 in ?? ()
#1  0x00007ffff735fb2b in hpx::lcos::base_lco::set_event_nonvirt (this=0x5555562af380) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/src/base_lco.cpp:46
#2  0x00007ffff73693b6 in hpx::actions::detail::component_invoke<hpx::lcos::base_lco, void, void ()>(void*, int, void (hpx::lcos::base_lco::*)()) (lva=0x5555562ba000, f=(void (hpx::lcos::base_lco::*)(hpx::lcos::base_lco * const)) 0x7ffff735fb08 <hpx::lcos::base_lco::set_event_nonvirt()>) at /home/biddisco/src/hpx-rma/libs/full/actions_base/include/hpx/actions_base/component_action.hpp:70
#3  0x00007ffff7368e80 in hpx::actions::action<void (hpx::lcos::base_lco::*)(), &hpx::lcos::base_lco::set_event_nonvirt, hpx::lcos::base_lco::set_event_action>::invoke<>(void*, int) (lva=0x5555562ba000, comptype=2) at /home/biddisco/src/hpx-rma/libs/full/actions_base/include/hpx/actions_base/component_action.hpp:103
#4  0x00007ffff736ac9f in hpx::actions::detail::action_invoke<hpx::lcos::base_lco::set_event_action>::operator()<>() const (this=0x7fffe572fe20) at /home/biddisco/src/hpx-rma/libs/full/actions_base/include/hpx/actions_base/basic_action.hpp:79
#5  hpx::util::detail::invoke_fused_impl<, hpx::actions::detail::action_invoke<hpx::lcos::base_lco::set_event_action>, hpx::tuple<> >(hpx::util::pack_c<unsigned long>, hpx::actions::detail::action_invoke<hpx::lcos::base_lco::set_event_action>&&, hpx::tuple<>&&) (t=..., f=...) at /home/biddisco/src/hpx-rma/libs/core/functional/include/hpx/functional/invoke_fused.hpp:66
#6  hpx::util::functional::invoke_fused::operator()<hpx::actions::detail::action_invoke<hpx::lcos::base_lco::set_event_action>, hpx::tuple<> >(hpx::actions::detail::action_invoke<hpx::lcos::base_lco::set_event_action>&&, hpx::tuple<>&&) const (t=..., f=..., this=0x7fffe572fe0f) at /home/biddisco/src/hpx-rma/libs/core/functional/include/hpx/functional/invoke_fused.hpp:131
#7  hpx::actions::trigger<void, hpx::util::functional::invoke_fused, hpx::actions::detail::action_invoke<hpx::lcos::base_lco::set_event_action>, hpx::tuple<> >(hpx::actions::typed_continuation<void, hpx::util::unused_type>&&, hpx::util::functional::invoke_fused&&, hpx::actions::detail::action_invoke<hpx::lcos::base_lco::set_event_action>&&, hpx::tuple<>&&) (cont=..., f=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/trigger.hpp:45
#8  0x00007ffff736a022 in hpx::traits::action_trigger_continuation<hpx::actions::typed_continuation<void, hpx::util::unused_type>, void>::call<hpx::util::functional::invoke_fused, hpx::actions::detail::action_invoke<hpx::lcos::base_lco::set_event_action>, hpx::tuple<> >(hpx::actions::typed_continuation<void, hpx::util::unused_type>&&, hpx::util::functional::invoke_fused&&, hpx::actions::detail::action_invoke<hpx::lcos::base_lco::set_event_action>&&, hpx::tuple<>&&) (f=..., cont=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/traits/action_trigger_continuation.hpp:28
#9  hpx::actions::detail::continuation_thread_function<hpx::lcos::base_lco::set_event_action>::operator()<hpx::threads::thread_restart_state, void> (this=0x5555562a5650) at /home/biddisco/src/hpx-rma/libs/full/actions_base/include/hpx/actions_base/basic_action.hpp:181
#10 0x00007ffff73698ed in hpx::util::detail::callable_vtable<std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> (hpx::threads::thread_restart_state)>::_invoke<hpx::actions::detail::continuation_thread_function<hpx::lcos::base_lco::set_event_action> >(void*, hpx::threads::thread_restart_state&&) (f=0x5555562a5650, vs#0=@0x7fffe572fec3: hpx::threads::thread_restart_state::signaled) at /home/biddisco/src/hpx-rma/libs/core/functional/include/hpx/functional/detail/vtable/callable_vtable.hpp:93
#11 0x00007ffff6880b91 in hpx::util::detail::basic_function<std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> (hpx::threads::thread_restart_state), false, false>::operator()(hpx::threads::thread_restart_state) const (vs#0=hpx::threads::thread_restart_state::signaled, this=0x55555ee2a0b8) at /home/biddisco/src/hpx-rma/libs/core/functional/include/hpx/functional/detail/basic_function.hpp:228
#12 hpx::threads::coroutines::detail::coroutine_impl::operator() (this=0x55555ee2a050) at /home/biddisco/src/hpx-rma/libs/core/coroutines/src/detail/coroutine_impl.cpp:74
#13 0x00007ffff68805ad in hpx::threads::coroutines::detail::lx::trampoline<hpx::threads::coroutines::detail::coroutine_impl> (fun=0x55555ee2a050) at /home/biddisco/src/hpx-rma/libs/core/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp:179
#14 0x0000000000000000 in ?? ()

```

**Comment by biddisco** [comment]
Here's another segfault stacktrace from the same command-line invocation of 4 ranks ... 
```
#0  0x000055555559fb6d in __gnu_cxx::__atomic_add (__val=1, __mem=0x9) at /usr/include/c++/11/ext/atomicity.h:71
#1  __gnu_cxx::__atomic_add_dispatch (__val=1, __mem=0x9) at /usr/include/c++/11/ext/atomicity.h:111
#2  std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_add_ref_copy (this=0x1) at /usr/include/c++/11/bits/shared_ptr_base.h:148
#3  0x00007ffff75a6793 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::operator= (this=0x7fffe8a7d358, __r=...) at /usr/include/c++/11/bits/shared_ptr_base.h:722
#4  0x00007ffff75aff61 in std::__shared_ptr<hpx::parcelset::policies::mpi::sender_connection, (__gnu_cxx::_Lock_policy)2>::operator= (this=0x7fffe8a7d350) at /usr/include/c++/11/bits/shared_ptr_base.h:1153
#5  0x00007ffff75aff8f in std::shared_ptr<hpx::parcelset::policies::mpi::sender_connection>::operator= (this=0x7fffe8a7d350) at /usr/include/c++/11/bits/shared_ptr.h:359
#6  0x00007ffff75b01e8 in hpx::util::connection_cache<hpx::parcelset::policies::mpi::sender_connection, hpx::parcelset::locality>::get_or_reserve (this=0x5555561cb000, l=..., conn=std::shared_ptr<hpx::parcelset::policies::mpi::sender_connection> (empty) = {...}, force_insert=false) at /home/biddisco/src/hpx-rma/libs/full/parcelset/include/hpx/parcelset/connection_cache.hpp:252
#7  0x00007ffff75ad661 in hpx::parcelset::parcelport_impl<hpx::parcelset::policies::mpi::parcelport>::get_connection (this=0x5555561cae00, l=..., ec=...) at /home/biddisco/src/hpx-rma/libs/full/parcelset/include/hpx/parcelset/parcelport_impl.hpp:546
#8  0x00007ffff75abce7 in hpx::parcelset::parcelport_impl<hpx::parcelset::policies::mpi::parcelport>::get_connection_and_send_parcels (this=0x5555561cae00, locality_id=...) at /home/biddisco/src/hpx-rma/libs/full/parcelset/include/hpx/parcelset/parcelport_impl.hpp:789
#9  0x00007ffff75bdb63 in hpx::parcelset::parcelport_impl<hpx::parcelset::policies::mpi::parcelport>::put_parcel(hpx::parcelset::locality const&, hpx::parcelset::parcel, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>)::{lambda(hpx::parcelset::parcel&&, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&)#1}::operator()(hpx::parcelset::parcel&&, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&) const (__closure=0x5555562a8270, p=..., f=...) at /home/biddisco/src/hpx-rma/libs/full/parcelset/include/hpx/parcelset/parcelport_impl.hpp:249
#10 0x00007ffff75c0468 in hpx::util::detail::callable_vtable<void (hpx::parcelset::parcel&&, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&)>::_invoke<hpx::parcelset::parcelport_impl<hpx::parcelset::policies::mpi::parcelport>::put_parcel(hpx::parcelset::locality const&, hpx::parcelset::parcel, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>)::{lambda(hpx::parcelset::parcel&&, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&)#1}>(void*, hpx::parcelset::parcel&&, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&) (f=0x5555562a8270, vs#0=..., vs#1=...) at /home/biddisco/src/hpx-rma/libs/core/functional/include/hpx/functional/detail/vtable/callable_vtable.hpp:93
#11 0x00007ffff75fc30c in hpx::util::detail::basic_function<void (hpx::parcelset::parcel&&, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&), false, false>::operator()(hpx::parcelset::parcel&&, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&) const (vs#1=..., vs#0=..., this=0x5555562a8260) at /home/biddisco/src/hpx-rma/libs/core/functional/include/hpx/functional/detail/basic_function.hpp:228
#12 hpx::parcelset::detail::parcel_await_base<hpx::parcelset::parcel, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>, hpx::parcelset::detail::parcel_await>::done() (this=0x5555562a8250) at /home/biddisco/src/hpx-rma/libs/full/parcelset/src/detail/parcel_await.cpp:48
#13 0x00007ffff75fbba5 in hpx::parcelset::detail::parcel_await::apply (this=0x5555562a8250) at /home/biddisco/src/hpx-rma/libs/full/parcelset/src/detail/parcel_await.cpp:113
#14 0x00007ffff75fb2e5 in hpx::parcelset::detail::parcel_await_apply(hpx::parcelset::parcel&&, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&, unsigned int, hpx::move_only_function<void (hpx::parcelset::parcel&&, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&), false>) (p=..., f=..., archive_flags=32768, pp=...) at /home/biddisco/src/hpx-rma/libs/full/parcelset/src/detail/parcel_await.cpp:152
#15 0x00007ffff75bdc8f in hpx::parcelset::parcelport_impl<hpx::parcelset::policies::mpi::parcelport>::put_parcel(hpx::parcelset::locality const&, hpx::parcelset::parcel, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>) (this=0x5555561cae00, dest=..., p=..., f=...) at /home/biddisco/src/hpx-rma/libs/full/parcelset/include/hpx/parcelset/parcelport_impl.hpp:237
#16 0x00007ffff760769b in hpx::parcelset::parcelhandler::put_parcel_impl(hpx::parcelset::parcel&&, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&) (this=0x555555f72140, p=..., f=...) at /home/biddisco/src/hpx-rma/libs/full/parcelset/src/parcelhandler.cpp:640
#17 0x00007ffff76071cb in hpx::parcelset::parcelhandler::put_parcel(hpx::parcelset::parcel, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>) (this=0x555555f72140, p=..., f=...) at /home/biddisco/src/hpx-rma/libs/full/parcelset/src/parcelhandler.cpp:568
#18 0x00007ffff779b24a in hpx::parcelset::detail::impl::put_parcel(hpx::parcelset::parcel&&, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&) (p=..., f=...) at /home/biddisco/src/hpx-rma/libs/full/runtime_distributed/src/locality_interface.cpp:113
#19 0x00007ffff7600570 in hpx::parcelset::put_parcel(hpx::parcelset::parcel&&, hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&) (p=..., f=...) at /home/biddisco/src/hpx-rma/libs/full/parcelset/src/message_handler.cpp:32
#20 0x00007ffff70f2faf in hpx::parcelset::detail::put_parcel_handler::operator() (this=0x7fffe8a7da37, p=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/put_parcel.hpp:151
#21 0x00007ffff71312a7 in hpx::parcelset::detail::put_parcel_impl<hpx::parcelset::detail::put_parcel_handler> (pp=..., dest=..., addr=..., action=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/put_parcel.hpp:114
#22 0x00007ffff741fd7d in hpx::parcelset::put_parcel<hpx::lcos::base_lco::set_event_action&, hpx::threads::thread_priority&> (dest=..., addr=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/put_parcel.hpp:171
#23 0x00007ffff741f67d in hpx::traits::action_put_parcel<hpx::lcos::base_lco::set_event_action, void>::call<>(hpx::naming::id_type const&, hpx::naming::address&&, hpx::threads::thread_priority) (id=..., addr=..., priority=hpx::threads::thread_priority::default_) at /home/biddisco/src/hpx-rma/libs/full/parcelset_base/include/hpx/parcelset_base/traits/action_put_parcel.hpp:45
#24 0x00007ffff741f4d9 in hpx::applier::detail::put_parcel<hpx::lcos::base_lco::set_event_action> (id=..., addr=..., priority=hpx::threads::thread_priority::default_) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/applier/apply.hpp:51
#25 0x00007ffff741d326 in hpx::applier::detail::apply_r_p<hpx::lcos::base_lco::set_event_action> (addr=..., id=..., priority=hpx::threads::thread_priority::default_) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/applier/apply.hpp:117
#26 0x00007ffff741bddf in hpx::detail::apply_impl<hpx::lcos::base_lco::set_event_action> (id=..., addr=..., priority=hpx::threads::thread_priority::default_) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/applier/detail/apply_implementations.hpp:227
#27 0x00007ffff741b0e9 in hpx::trigger_lco_event (id=..., addr=..., move_credits=true) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/src/trigger_lco.cpp:40
#28 0x00007ffff741a3e0 in hpx::actions::typed_continuation<void, hpx::util::unused_type>::trigger (this=0x55555ee2ad88) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/src/continuation.cpp:142
#29 0x00005555555d1b44 in hpx::actions::trigger<void, hpx::util::functional::invoke_fused, hpx::actions::detail::action_invoke<performance_action>, hpx::tuple<perf, test_options> > (cont=..., f=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/trigger.hpp:46
#30 0x00005555555c82e2 in hpx::traits::action_trigger_continuation<hpx::actions::typed_continuation<void, hpx::util::unused_type>, void>::call<hpx::util::functional::invoke_fused, hpx::actions::detail::action_invoke<performance_action>, hpx::tuple<perf, test_options> > (f=..., cont=...) at /home/biddisco/src/hpx-rma/libs/full/async_distributed/include/hpx/async_distributed/traits/action_trigger_continuation.hpp:28
#31 hpx::actions::detail::continuation_thread_function<performance_action>::operator()<hpx::threads::thread_restart_state, void> (this=0x55555ee2ad80) at /home/biddisco/src/hpx-rma/libs/full/actions_base/include/hpx/actions_base/basic_action.hpp:181
#32 0x00005555555c40f8 in hpx::util::detail::callable_vtable<std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> (hpx::threads::thread_restart_state)>::_invoke<hpx::actions::detail::continuation_thread_function<performance_action> >(void*, hpx::threads::thread_restart_state&&) (f=0x55555ee2ad80, vs#0=@0x7fffe8a7dec3: hpx::threads::thread_restart_state::signaled) at /home/biddisco/src/hpx-rma/libs/core/functional/include/hpx/functional/detail/vtable/callable_vtable.hpp:93
#33 0x00007ffff6880b91 in hpx::util::detail::basic_function<std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> (hpx::threads::thread_restart_state), false, false>::operator()(hpx::threads::thread_restart_state) const (vs#0=hpx::threads::thread_restart_state::signaled, this=0x55555ed610f8) at /home/biddisco/src/hpx-rma/libs/core/functional/include/hpx/functional/detail/basic_function.hpp:228
#34 hpx::threads::coroutines::detail::coroutine_impl::operator() (this=0x55555ed61090) at /home/biddisco/src/hpx-rma/libs/core/coroutines/src/detail/coroutine_impl.cpp:74
#35 0x00007ffff68805ad in hpx::threads::coroutines::detail::lx::trampoline<hpx::threads::coroutines::detail::coroutine_impl> (fun=0x55555ed61090) at /home/biddisco/src/hpx-rma/libs/core/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp:179
#36 0x0000000000000000 in ?? ()
```

**Comment by biddisco** [comment]
closing this temporarily as it might have been caused by a bug in my test code. will reopen if the main action related failure reappers
