### ISSUE TITLE
component with multiple inheritance

### ISSUE THREAD

**Issue by kleinhenz** [STEllAR-GROUP/hpx#5964]
## Expected Behavior

Previously I have successfully used components with multiple inheritance but this appears to cause problems in HPX 1.8.0.

## Actual Behavior

Components which inherit from another class cause segfaults (the backtraces seems to generally point back to the class destructor). 

## Steps to Reproduce the Problem

See this test case which works in HPX 1.7.0 but fails in HPX 1.8.0. This test case passes if I inherit from `component_base` first but this makes me feel like I am relying on some fragile behavior which may not really be working properly. Is this meant to be supported?

```
#include <hpx/config.hpp>
#if !defined(HPX_COMPUTE_DEVICE_CODE)
#include <hpx/hpx_init.hpp>
#include <hpx/include/actions.hpp>
#include <hpx/include/async.hpp>
#include <hpx/include/components.hpp>
#include <hpx/include/runtime.hpp>
#include <hpx/include/util.hpp>
#include <hpx/modules/testing.hpp>

#include <atomic>
#include <cstddef>
#include <vector>

///////////////////////////////////////////////////////////////////////////////

struct foo_t {
  int a;
  int b;
  foo_t() = default;
  foo_t(int a, int b) : a(a), b(b) {}

  friend class hpx::serialization::access;
  template<typename Archive> inline void serialize(Archive &ar, const unsigned int) {
    ar & a & b;
  }
};

struct component_server : foo_t, hpx::components::component_base<component_server> {
  component_server(foo_t foo) : foo_t(std::move(foo)) {}
};

HPX_REGISTER_COMPONENT(
    hpx::components::component<component_server>, component_server_component)

int hpx_main()
{
    foo_t in {1,2};
    hpx::id_type id = hpx::new_<component_server>(hpx::find_here(), in).get();
    const component_server& out = *hpx::get_ptr<component_server>(hpx::launch::sync_policy(), id);
    HPX_TEST_EQ(out.a, in.a);
    HPX_TEST_EQ(out.b, in.b);

    return hpx::finalize();
}

int main(int argc, char** argv)
{
    HPX_TEST_EQ(hpx::init(argc, argv), 0);
    return hpx::util::report_errors();
}
#endif
```

## Specifications

Please describe your environment:

  - HPX Version: 1.8.0
  - Platform (compiler, OS): gcc 12.1.1, opensuse tumbleweed

**Comment by kleinhenz** [comment]
bisected to c8650bc311fd8ef344fadc48be46cba986d89339. I can also reproduce with clang 14.0.6.

**Comment by hkaiser** [comment]
> bisected to [c8650bc](https://github.com/STEllAR-GROUP/hpx/commit/c8650bc311fd8ef344fadc48be46cba986d89339). I can also reproduce with clang 14.0.6.

This change is completely unrelated. Not sure why you think it's causing the issue.

**Comment by kleinhenz** [comment]
I mean I agree that it looks completely unrelated, I'm just letting you know that is the commit where the issue is first visible to me based on bisecting between 1.7.0 and 1.8.0.

**Comment by kleinhenz** [comment]
ok after fixing an issue with the compiler flags I now bisect to a9e420671bfea989e544d1b7aac647a2def58e8a which looks more reasonable.

**Comment by hkaiser** [comment]
> ok after fixing an issue with the compiler flags I now bisect to [a9e4206](https://github.com/STEllAR-GROUP/hpx/commit/a9e420671bfea989e544d1b7aac647a2def58e8a) which looks more reasonable.

True, this commit could indeed cause problems. I'll investigate. Thanks!

**Comment by kleinhenz** [comment]
asan report below. I confirmed that the test runs clean with asan with the previous commit.

```
/home/joseph/Documents/spike/hpx/src/spike.cpp(40): test 'out.a == in.a' failed in function 'int hpx_main()': '36' != '1'
/home/joseph/Documents/spike/hpx/src/spike.cpp(41): test 'out.b == in.b' failed in function 'int hpx_main()': '1' != '2'
=================================================================
==4239==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6030000b2468 at pc 0x7f514c118ac4 bp 0x7f513dc185c0 sp 0x7f513dc185b8
READ of size 8 at 0x6030000b2468 thread T9
    #0 0x7f514c118ac3 in hpx::naming::gid_type::operator bool() const /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/naming_base/include/hpx/naming_base/gid_type.hpp:130
    #1 0x7f514c118ac3 in hpx::components::detail::base_component::~base_component() /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/components_base/src/server/component_base.cpp:25
    #2 0x4375b5 in hpx::components::component_base<component_server>::~component_base() /home/joseph/.local/opt/spack/var/spack/environments/hpx0/.spack-env/view/include/hpx/components_base/server/component_base.hpp:105
    #3 0x4375b5 in component_server::~component_server() /home/joseph/Documents/spike/hpx/src/spike.cpp:28
    #4 0x4375b5 in hpx::components::component<component_server>::~component() /home/joseph/.local/opt/spack/var/spack/environments/hpx0/.spack-env/view/include/hpx/components_base/server/component.hpp:61
    #5 0x4375b5 in void hpx::components::server::destroy<hpx::components::component<component_server> >(hpx::naming::gid_type const&, hpx::naming::address const&) /home/joseph/.local/opt/spack/var/spack/environments/hpx0/.spack-env/view/include/hpx/async_colocated/server/destroy_component.hpp:58
    #6 0x7f514baeb7b0 in hpx::agas::server::primary_namespace::free_components_sync(std::__cxx11::list<hpx::agas::server::primary_namespace::free_entry, std::allocator<hpx::agas::server::primary_namespace::free_entry> >&, hpx::naming::gid_type const&, hpx::naming::gid_type const&, hpx::error_code&) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/agas_base/src/server/primary_namespace_server.cpp:1012
    #7 0x7f514baf5ebd in hpx::agas::server::primary_namespace::decrement_credit(std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > const&) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/agas_base/src/server/primary_namespace_server.cpp:579
    #8 0x7f514b6a3702 in std::vector<long, std::allocator<long> > hpx::actions::detail::component_invoke<hpx::agas::server::primary_namespace, std::vector<long, std::allocator<long> >, std::vector<long, std::allocator<long> > (std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > const&), std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > >(void*, int, std::vector<long, std::allocator<long> > (hpx::agas::server::primary_namespace::*)(std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > const&), std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > >&&) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/actions_base/include/hpx/actions_base/component_action.hpp:70
    #9 0x7f514b6a3702 in std::vector<long, std::allocator<long> > hpx::actions::action<std::vector<long, std::allocator<long> > (hpx::agas::server::primary_namespace::*)(std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > const&), &hpx::agas::server::primary_namespace::decrement_credit, hpx::agas::server::primary_namespace::decrement_credit_action>::invoke<std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > >(void*, int, std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > >&&) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/actions_base/include/hpx/actions_base/component_action.hpp:104
    #10 0x7f514b6a3702 in std::vector<long, std::allocator<long> > hpx::actions::detail::action_invoke<hpx::agas::server::primary_namespace::decrement_credit_action>::operator()<std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > >(std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > >&&) const /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/actions_base/include/hpx/actions_base/basic_action.hpp:79
    #11 0x7f514b6a3702 in hpx::util::detail::invoke_fused_result<hpx::actions::detail::action_invoke<hpx::agas::server::primary_namespace::decrement_credit_action>, hpx::tuple<std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > > >::type hpx::util::detail::invoke_fused_impl<0ul, hpx::actions::detail::action_invoke<hpx::agas::server::primary_namespace::decrement_credit_action>, hpx::tuple<std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > > >(hpx::util::pack_c<unsigned long, 0ul>, hpx::actions::detail::action_invoke<hpx::agas::server::primary_namespace::decrement_credit_action>&&, hpx::tuple<std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > >&&) /home/joseph/Documents/projects/noneq/code/hpx/release/build/_deps/hpxlocal-src/libs/core/functional/include/hpx/functional/invoke_fused.hpp:61
    #12 0x7f514b6a3702 in hpx::util::detail::invoke_fused_result<hpx::actions::detail::action_invoke<hpx::agas::server::primary_namespace::decrement_credit_action>, hpx::tuple<std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > > >::type hpx::util::functional::invoke_fused::operator()<hpx::actions::detail::action_invoke<hpx::agas::server::primary_namespace::decrement_credit_action>, hpx::tuple<std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > > >(hpx::actions::detail::action_invoke<hpx::agas::server::primary_namespace::decrement_credit_action>&&, hpx::tuple<std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > >&&) const /home/joseph/Documents/projects/noneq/code/hpx/release/build/_deps/hpxlocal-src/libs/core/functional/include/hpx/functional/invoke_fused.hpp:119
    #13 0x7f514b6a3702 in void hpx::actions::trigger<std::vector<long, std::allocator<long> >, std::vector<long, std::allocator<long> >, hpx::util::functional::invoke_fused, hpx::actions::detail::action_invoke<hpx::agas::server::primary_namespace::decrement_credit_action>, hpx::tuple<std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > > >(hpx::actions::typed_continuation<std::vector<long, std::allocator<long> >, std::vector<long, std::allocator<long> > >&&, hpx::util::functional::invoke_fused&&, hpx::actions::detail::action_invoke<hpx::agas::server::primary_namespace::decrement_credit_action>&&, hpx::tuple<std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > >&&) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/async_distributed/include/hpx/async_distributed/trigger.hpp:28
    #14 0x7f514b6a3702 in void hpx::traits::action_trigger_continuation<hpx::actions::typed_continuation<std::vector<long, std::allocator<long> >, std::vector<long, std::allocator<long> > >, void>::call<hpx::util::functional::invoke_fused, hpx::actions::detail::action_invoke<hpx::agas::server::primary_namespace::decrement_credit_action>, hpx::tuple<std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > > >(hpx::actions::typed_continuation<std::vector<long, std::allocator<long> >, std::vector<long, std::allocator<long> > >&&, hpx::util::functional::invoke_fused&&, hpx::actions::detail::action_invoke<hpx::agas::server::primary_namespace::decrement_credit_action>&&, hpx::tuple<std::vector<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type>, std::allocator<hpx::tuple<long, hpx::naming::gid_type, hpx::naming::gid_type> > > >&&) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/async_distributed/include/hpx/async_distributed/traits/action_trigger_continuation.hpp:28
    #15 0x7f514b6a3702 in std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> hpx::actions::detail::continuation_thread_function<hpx::agas::server::primary_namespace::decrement_credit_action>::operator()<hpx::threads::thread_restart_state, void>(hpx::threads::thread_restart_state) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/actions_base/include/hpx/actions_base/basic_action.hpp:181
    #16 0x7f514b6306a1 in std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> hpx::util::detail::callable_vtable<std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> (hpx::threads::thread_restart_state)>::_invoke<hpx::actions::detail::continuation_thread_function<hpx::agas::server::primary_namespace::decrement_credit_action> >(void*, hpx::threads::thread_restart_state&&) /home/joseph/Documents/projects/noneq/code/hpx/release/build/_deps/hpxlocal-src/libs/core/functional/include/hpx/functional/detail/vtable/callable_vtable.hpp:93
    #17 0x7f514aa9e3f7 in hpx::util::detail::basic_function<std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> (hpx::threads::thread_restart_state), false, false>::operator()(hpx::threads::thread_restart_state) const /home/joseph/Documents/projects/noneq/code/hpx/release/build/_deps/hpxlocal-src/libs/core/functional/include/hpx/functional/detail/basic_function.hpp:228
    #18 0x7f514aa9e3f7 in hpx::threads::coroutines::detail::coroutine_impl::operator()() /home/joseph/Documents/projects/noneq/code/hpx/release/build/_deps/hpxlocal-src/libs/core/coroutines/src/detail/coroutine_impl.cpp:74
    #19 0x7f514aa9bff8 in void hpx::threads::coroutines::detail::lx::trampoline<hpx::threads::coroutines::detail::coroutine_impl>(void*) /home/joseph/Documents/projects/noneq/code/hpx/release/build/_deps/hpxlocal-src/libs/core/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp:92

0x6030000b2468 is located 0 bytes to the right of 24-byte region [0x6030000b2450,0x6030000b2468)
allocated by thread T7 here:
    #0 0x7f514cc69ee8 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:95

Thread T9 created by T0 here:
    #0 0x7f514cbfa146 in __interceptor_pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:207
    #1 0x7f514a3e49e8 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib64/libstdc++.so.6+0xe09e8)
    #2 0x7f514ae85a97 in hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::run(std::unique_lock<std::mutex>&, unsigned long) /home/joseph/Documents/projects/noneq/code/hpx/release/build/_deps/hpxlocal-src/libs/core/thread_pools/include/hpx/thread_pools/scheduled_thread_pool_impl.hpp:329
    #3 0x7f514afd55d8 in hpx::threads::threadmanager::run() /home/joseph/Documents/projects/noneq/code/hpx/release/build/_deps/hpxlocal-src/libs/core/threadmanager/src/threadmanager.cpp:1036
    #4 0x7f514c5efad2 in hpx::runtime_distributed::start(hpx::util::function<int (), false> const&, bool) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/runtime_distributed/src/runtime_distributed.cpp:455
    #5 0x7f514c5d2862 in hpx::runtime_distributed::run(hpx::util::function<int (), false> const&) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/runtime_distributed/src/runtime_distributed.cpp:775
    #6 0x7f514c1aafbb in hpx::detail::run(hpx::runtime&, hpx::util::function<int (hpx::program_options::variables_map&), false> const&, hpx::program_options::variables_map&, hpx::runtime_mode, hpx::util::unique_function<void (), false>, hpx::util::unique_function<void (), false>) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/init_runtime/src/hpx_init.cpp:670
    #7 0x7f514c1ab934 in hpx::detail::run_or_start(bool, std::unique_ptr<hpx::runtime, std::default_delete<hpx::runtime> >, hpx::util::command_line_handling&, hpx::util::unique_function<void (), false>, hpx::util::unique_function<void (), false>) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/init_runtime/src/hpx_init.cpp:703
    #8 0x7f514c1ade46 in hpx::detail::run_or_start(hpx::util::function<int (hpx::program_options::variables_map&), false> const&, int, char**, hpx::init_params const&, bool) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/init_runtime/src/hpx_init.cpp:931
    #9 0x42df84 in hpx::detail::init_impl(hpx::util::function<int (hpx::program_options::variables_map&), false> const&, int, char**, hpx::init_params const&) /home/joseph/.local/opt/spack/var/spack/environments/hpx0/.spack-env/view/include/hpx/hpx_init_impl.hpp:79
    #10 0x42df84 in hpx::init(int, char**, hpx::init_params const&) /home/joseph/.local/opt/spack/var/spack/environments/hpx0/.spack-env/view/include/hpx/hpx_init_impl.hpp:119
    #11 0x40de43 in main /home/joseph/Documents/spike/hpx/src/spike.cpp:48
    #12 0x7f514a0095af in __libc_start_call_main (/lib64/libc.so.6+0x405af)

Thread T7 created by T0 here:
    #0 0x7f514cbfa146 in __interceptor_pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:207
    #1 0x7f514a3e49e8 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib64/libstdc++.so.6+0xe09e8)
    #2 0x7f514ae85a97 in hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::run(std::unique_lock<std::mutex>&, unsigned long) /home/joseph/Documents/projects/noneq/code/hpx/release/build/_deps/hpxlocal-src/libs/core/thread_pools/include/hpx/thread_pools/scheduled_thread_pool_impl.hpp:329
    #3 0x7f514afd55d8 in hpx::threads::threadmanager::run() /home/joseph/Documents/projects/noneq/code/hpx/release/build/_deps/hpxlocal-src/libs/core/threadmanager/src/threadmanager.cpp:1036
    #4 0x7f514c5efad2 in hpx::runtime_distributed::start(hpx::util::function<int (), false> const&, bool) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/runtime_distributed/src/runtime_distributed.cpp:455
    #5 0x7f514c5d2862 in hpx::runtime_distributed::run(hpx::util::function<int (), false> const&) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/runtime_distributed/src/runtime_distributed.cpp:775
    #6 0x7f514c1aafbb in hpx::detail::run(hpx::runtime&, hpx::util::function<int (hpx::program_options::variables_map&), false> const&, hpx::program_options::variables_map&, hpx::runtime_mode, hpx::util::unique_function<void (), false>, hpx::util::unique_function<void (), false>) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/init_runtime/src/hpx_init.cpp:670
    #7 0x7f514c1ab934 in hpx::detail::run_or_start(bool, std::unique_ptr<hpx::runtime, std::default_delete<hpx::runtime> >, hpx::util::command_line_handling&, hpx::util::unique_function<void (), false>, hpx::util::unique_function<void (), false>) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/init_runtime/src/hpx_init.cpp:703
    #8 0x7f514c1ade46 in hpx::detail::run_or_start(hpx::util::function<int (hpx::program_options::variables_map&), false> const&, int, char**, hpx::init_params const&, bool) /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/init_runtime/src/hpx_init.cpp:931
    #9 0x42df84 in hpx::detail::init_impl(hpx::util::function<int (hpx::program_options::variables_map&), false> const&, int, char**, hpx::init_params const&) /home/joseph/.local/opt/spack/var/spack/environments/hpx0/.spack-env/view/include/hpx/hpx_init_impl.hpp:79
    #10 0x42df84 in hpx::init(int, char**, hpx::init_params const&) /home/joseph/.local/opt/spack/var/spack/environments/hpx0/.spack-env/view/include/hpx/hpx_init_impl.hpp:119
    #11 0x40de43 in main /home/joseph/Documents/spike/hpx/src/spike.cpp:48
    #12 0x7f514a0095af in __libc_start_call_main (/lib64/libc.so.6+0x405af)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/joseph/Documents/projects/noneq/code/hpx/release/libs/full/naming_base/include/hpx/naming_base/gid_type.hpp:130 in hpx::naming::gid_type::operator bool() const
Shadow bytes around the buggy address:
  0x0c068000e430: fd fd fd fa fa fa fd fd fd fa fa fa fd fd fd fa
  0x0c068000e440: fa fa fd fd fd fa fa fa fd fd fd fa fa fa fd fd
  0x0c068000e450: fd fa fa fa fd fd fd fd fa fa fd fd fd fd fa fa
  0x0c068000e460: fd fd fd fd fa fa fd fd fd fa fa fa fd fd fd fa
  0x0c068000e470: fa fa fd fd fd fa fa fa fd fd fd fd fa fa fd fd
=>0x0c068000e480: fd fa fa fa fd fd fd fa fa fa 00 00 00[fa]fa fa
  0x0c068000e490: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fa
  0x0c068000e4a0: fa fa fd fd fd fd fa fa fd fd fd fa fa fa fd fd
  0x0c068000e4b0: fd fd fa fa fd fd fd fa fa fa fd fd fd fd fa fa
  0x0c068000e4c0: fd fd fd fa fa fa fd fd fd fa fa fa fd fd fd fa
  0x0c068000e4d0: fa fa fd fd fd fd fa fa fd fd fd fa fa fa fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==4239==ABORTING
```

**Comment by hkaiser** [comment]
@kleinhenz I think I know what's causing this. Thanks!
